name: Release Plugin

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on version tags like v1.0.0, v2.1.0, etc.

permissions:
  contents: write  # Ensure the workflow has permission to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Create a zip file of the plugin
      - name: Create zip file
        run: |
          mkdir dist
          zip -r dist/interactive-map-plugin.zip . -x "*.git*" -x "*.github/*"

      # Step 3: Create a GitHub release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/interactive-map-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}